### ISSUE TITLE
네이버 영화 검색 API 탑재 관련 

### ISSUE THREAD

**Issue by komplamoose** [DDAGUE/OSP_final#2]
저번 중간 평가에서 교수님께서 사용자가 영화 url을 찾는 것이 어렵다고 지적해주신 부분을 보완하기 위해

메인 웹페이지에서 네이버 영화 API를 통해 검색을 제공하고, 이걸 통해 직접 url을 찾을 수 있게 구현하면 사용자 접근성이 높아질 것 같습니다. 

관련 의견 부탁드립니다.

**Comment by DDAGUE** [comment]
네 관련해서 찾아보겠습니다~
